{include file='Common/header' /}
<div class="breadcrumb">
    <div class="container">
        <span><a href="{:LU('/')}">{$data.lang.HOMEPAGE}</a></span>
        <img src="__PUBLIC__/img/icon_arrow_right_s.png" />
        <span>{$data.lang.ABOUT_US}</span>
    </div>
</div>

<div class="container page-content">
    <h2 class="page-title">{$data.lang.ABOUT_US}</h2>
    <div class="page-body">

Squirreal International Real Estate is a global real estate asset allocation service platform. It was established in 2019 with the aim to assist investors diversify portfolios and allocate assets in overseas real estate assets to fulfill their personal financial goals. Squirreal partner with local experts globally and provide investors with value-for-money properties for various purposes – stable cash flow, capital gain or passport/visa procurement. The platform is established by experienced professionals from real estate, information technology and marketing industries.
<br/>
<br/>

<b>Partner/Founder, Michael JIA</b>
<br/>
Michael has 15 years of real estate industry experience including investment, asset management and fund raising. He has served in various reputable Chinese and international real estate development companies, funds and asset management companies including BlackRock and Ping’an Real Estate. Michael holds an MSc International Real Estate degree from Oxford Brookes University, UK. 
<br/>
<br/>

<b>Partner/CTO, Sylvain YAO</b>
<br/>
Sylvain has 7 years of experience in development and management, including software, application, website design, development and devops. He has worked for Fangdd, a leading listed internet company in China, and PWC Acceleration Center Shanghai, an international IT consulting company. Sylvain holds a French engineer degree (certified as a master in China). He has extensive experience in leading teams to produce first-class digital products.
<br/>
<br/>

<b>Partner/CMO, Helen LIU</b>
<br/>
Helen has more than 14 years of experience in marketing and branding field with solid track record in marketing strategy, business development, and digital and social media campaigns. She has strong understanding of both western and eastern cultures following a career with multi-national companies, including Limetree Capital, Activation and IMC Group. Helen holds a bachelor’s degree in hospitality management from Shanghai University and William Angliss Institute, Australia. 
<br/>
<br/>
    </div>
</div>

{include file='Common/footer' /}