{include file='Common/header' /}
<div class="breadcrumb">
    <div class="container">
        <span><a href="{:LU('/')}">{$data.lang.HOMEPAGE}</a></span>
        <img src="__PUBLIC__/img/icon_arrow_right_s.png" />
        <span>{$data.lang.ABOUT_US}</span>
    </div>
</div>

<div class="container page-content">
    <h2 class="page-title">{$data.lang.ABOUT_US}</h2>
    <div class="page-body">

Squirreal International Real Estate is a global real estate asset allocation service platform. It was established in 2019 with the aim to assist investors diversify portfolios and allocate assets in overseas real estate assets to fulfill their personal financial goals. Squirreal partner with local experts globally and provide investors with value-for-money properties for various purposes – stable cash flow, capital gain or passport/visa procurement. The platform is established by experienced professionals from real estate, information technology and marketing industries.
<br/>
松鼠国际房地产是一个全球房地产资产配置的服务平台。平台于2019年建立，目标是协助投资者将部分资产配置于国际房地产、多元化资产组合，从而实现个人的财务目标。松鼠与全球各地的当地专家合作，为投资者提供高性价比的房地产项目以满足投资者的各种需求 – 稳定的现金流、资产增值或是获取护照/签证。该平台由来自房地产、信息技术和营销等行业的经验丰富的专业人士搭建。
<br/>
<br/>

<b>Partner/Founder, Michael JIA 合伙人/创始人，贾敏</b>
<br/>
Michael has 15 years of real estate industry experience including investment, asset management and fund raising. He has served in various reputable Chinese and international real estate development companies, funds and asset management companies including BlackRock and Ping’an Real Estate. Michael holds an MSc International Real Estate degree from Oxford Brookes University, UK. 
<br/>
贾敏拥有15年房地产行业的从业经验，包括投资、资产管理和资金募集。他曾在多家有名的中资及国际房地产开发商、基金和资产管理公司就职，包括贝莱德和平安不动产。贾敏持有英国牛津布鲁克斯大学的国际房地产硕士学位。
<br/>
<br/>

<b>Partner/CTO, Sylvain YAO 合伙人/技术总监，姚昊辰</b>
<br/>
Sylvain has 7 years of experience in development and management, including software, application, website design, development and devops. He has worked for Fangdd, a leading listed internet company in China, and PWC Acceleration Center Shanghai, an international IT consulting company. Sylvain holds a French engineer degree (certified as a master in China). He has extensive experience in leading teams to produce first-class digital products.
姚昊辰拥有法国工程师学位（中国认证为硕士）。他在开发和团队管理方面拥有7年的经验，其中包括软件、应用程序、网站的设计、开发以及系统运维。 他曾在500强公司安塞罗米塔尔集团，中国领先的互联网上市公司房多多和国际知名信息技术咨询公司普华永道全球信息技术优创中心工作。他在领导一流的数字产品生产团队上拥有丰富的经验。
<br/>
<br/>

<b>Partner/CMO, Helen LIU 合伙人/营销总监，刘娟娟</b>
<br/>
Helen has more than 14 years of experience in marketing and branding field with solid track record in marketing strategy, business development, and digital and social media campaigns. She has strong understanding of both western and eastern cultures following a career with multi-national companies, including Limetree Capital, Activation and IMC Group. Helen holds a bachelor’s degree in hospitality management from Shanghai University and William Angliss Institute, Australia. 
<br/>
刘娟娟在市场拓展、品牌营销、在线推广及社交媒体等领域有逾14年的专业经验。先后任职于览睿资本、艾德韦宣集团和新加坡万邦集团等国内外知名上市及跨国企业。刘女士拥有上海大学及澳大利亚威廉安格里斯学院的酒店管理学士学位。
<br/>
<br/>
    </div>
</div>

{include file='Common/footer' /}