{include file='Common/header' /}
<div class="breadcrumb">
    <div class="container">
	    <span><a rel="nofollow" href="{:LU('/')}">{$data.lang.HOMEPAGE}</a></span>
        <img src="__PUBLIC__/img/icon_arrow_right_s.png" />
        <span>{$data.lang.AGREEMENT}</span>
    </div>
</div>

<div class="container page-content">
    <h2 class="page-title">{$data.lang.AGREEMENT}</h2>
    <div class="page-body">

    </div>
</div>

{include file='Common/footer' /}