{include file='Common/header_m' /}

<?php if($data['banner']):?>
<div class="swiper">
	<div class="swiper-container">
		<div class="swiper-wrapper">
			<?php foreach ($data['banner'] as $k => $v):?>
			<div class="swiper-slide">
				<?php if($v['type'] == 1):?>
				<div class="image link-item" data-url="{:U($v['target'].'/'.$v['targetId'])}" style="background-image: url('{$v.file}')"></div>
				<?php elseif ($v['type'] == 2):?>
				<div class="video" data-file="{$v.file}" style="background-image: url('{$v.file}?x-oss-process=video/snapshot,t_1000')">
					<img src="__PUBLIC__/img/icon_play.png" />
				</div>
				<?php endif;?>
			</div>
			<?php endforeach;?>
		</div>
	</div>
</div><!-- //轮播 -->
<?php endif;?>

<?php if($data['hot_country']):?>

<div class="card hot-country">
	<div class="card-title">{$data.lang.HOT_COUNTRY}</div>
	<div class="card-body">
		<?php foreach ($data['hot_country'] as $k => $item):?>
		<div class="card-item">
			<div class="circle-item link-item" style="background-image:url({$item.cover})" data-url="{:U('country/'.$item['id'])}">
				<span class="txt-name"></span>
			</div>
			<div class="item-name">{$item.name}</div>
			<div class="item-flag">{$item.intro}</div>
		</div>
		<?php endforeach;?>
	</div>
</div><!-- //热门国家 -->

<?php endif;?>

<?php if($data['hot_city']):?>

<div class="card hot-city">
	<div class="card-title">{$data.lang.HOT_CITY}</div>
	<div class="card-body">
		<?php foreach ($data['hot_city'] as $k => $item):?>
		<div class="card-item">
			<div class="circle-item link-item" style="background-image:url({$item.cover})" data-url="{:U('city/'.$item['id'])}">
				<span class="txt-name"></span>
			</div>
			<div class="item-name">{$item.name}</div>
		</div>
        <?php endforeach;?>
	</div>
</div><!-- //热门城市 -->
<?php endif;?>

<?php if($data['hot_buildings']):?>
<div class="card hot-buildings">
	<div class="card-title">{$data.lang.BEST_BUILDINGS}</div>
	<div class="card-body">
		<?php foreach ($data['hot_buildings'] as $k => $item):?>
		<div class="building-item link-item" data-url="{:U('building/'.$item['id'])}">
			<div class="building-cover" style="background-image:url({$item.cover})">
				<?php if($item['tag']):?>
				<span class="building-tag">{$item.tag}</span>
				<?php endif;?>
			</div>
			<div class="building-info">
				<div class="building-name"><span>{$item.name}</span></div>
				<div class="building-location"><span>{$item.location}</span></div>
				<div class="building-price"><span>{$item.price}</span><span class="sp">{$data.lang.SP}</span></div>
				<button class="btn">{$data.lang.VIEW_MORE}</button>
			</div>
		</div>
        <?php endforeach;?>
	</div>
</div><!-- //精品楼盘 -->

<?php endif;?>

{include file='Common/footer_m' /}