{include file='Common/header' /}

<div class="home-banner">
	<div class="inner">
		<div class="container full">
			<a href="{:LU('/')}" class="logo fl"><img src="__PUBLIC__/img/img_logo_white.png" /> </a>
			<div class="menu fr">
				<a href="javascript:" class="btn-lang-switcher">
					<svg viewBox="0 0 12 12" class="icon-lang"><path d="M3.48 3.5c.17-.85.43-1.6.75-2.18A5.02 5.02 0 001.67 3.5zm1.03 0h2.98C7.16 2 6.57 1 6 1S4.84 2 4.5 3.5zm4 0h1.82a5.02 5.02 0 00-2.56-2.18c.32.58.58 1.33.75 2.18zm.16 1a13.82 13.82 0 010 3h2.1a5 5 0 000-3zm-1.01 0H4.34a12.43 12.43 0 000 3h3.32a12.43 12.43 0 000-3zm-4.33 0h-2.1a5 5 0 000 3h2.1a13.82 13.82 0 010-3zm5.19 4a7.5 7.5 0 01-.75 2.18 5.02 5.02 0 002.56-2.18zm-1.03 0H4.51C4.84 10 5.43 11 6 11s1.16-1 1.5-2.5zm-4 0H1.66c.57 1 1.48 1.77 2.56 2.18a7.5 7.5 0 01-.75-2.18zM6 12A6 6 0 116 0a6 6 0 010 12z" fill="currentcolor"></path></svg>
					<span>{$data.current_lang_name}</span>
				</a>
                <?php if($data['userinfo']):?>
				<div class="userinfo">
					<span>{$data.userinfo.nickname}</span>
					<img src="{$data.userinfo.avatar}" />
				</div>
                <?php else:?>
				<a href="javascript:" class="btn-login">{$data.lang.SIGN_IN}</a>
				<a href="javascript:" class="btn-login">{$data.lang.SIGN_UP}</a>
				<?php endif;?>
			</div>
		</div>
		<div class="container">
			<div class="feature">
				<h1>{$data.lang.SQUIRREAL}</h1>
				<h2>{$data.lang.PROGRAM_INTRO}</h2>
			</div>

		</div>
	</div>
</div>

<?php if($data['hot_country']):?>
<div class="section hot-country">
	<div class="container">
		<h2 class="section-title">{$data.lang.HOT_COUNTRY}</h2>
		<div class="section-body">
			<div class="swiper-country">
				<div class="swiper-container">
					<div class="swiper-wrapper">
                        <?php foreach ($data['hot_country'] as $k => $v):?>
						<div class="swiper-slide">
							<a href="{:LU('/country/'.$v['id'])}" class="swiper-no-swiping" title="{$v.full_name}">
								<div class="cover" style="background-image:url({$v.web_cover_img})"></div>
								<div class="inner">
									<h3>{$v.full_name}</h3>
									<p>{$v.intro}</p>
								</div>
							</a>
						</div>
                        <?php endforeach;?>
					</div>
				</div>
				<!-- Navigation -->
				<div class="swiper-button-next"></div>
				<div class="swiper-button-prev"></div>
			</div>

		</div>
	</div>
</div>
<?php endif;?>

<?php if($data['hot_city']):?>
<div class="section hot-city">
	<div class="container">
		<h2 class="section-title">{$data.lang.HOT_CITY}</h2>
		<div class="section-body">
			<div class="swiper-country">
				<div class="swiper-container">
					<div class="swiper-wrapper">
                        <?php foreach ($data['hot_city'] as $k => $v):?>
							<div class="swiper-slide">
								<a href="{:LU('/city/'.$v['id'])}" class="swiper-no-swiping" title="{$v.full_name}">
									<div class="cover" style="background-image:url({$v.web_cover_img})"></div>
									<div class="inner">
										<h3>{$v.full_name}</h3>
										<p>{$v.country_name}</p>
									</div>
								</a>
							</div>
                        <?php endforeach;?>
					</div>
				</div>
				<!-- Navigation -->
				<div class="swiper-button-next"></div>
				<div class="swiper-button-prev"></div>
			</div>
		</div>
	</div>
</div>
<?php endif;?>

<?php if(false && $data['presales']):?>
<div class="section waypoint presales-list" id="presales-list">
	<div class="container">
		<h2 class="section-title">{$data.lang.PRESALES_LIST}</h2>
		<div class="section-body">
            <?php foreach ($data['presales'] as $k => $item):?>
			<a class="presale-item" href="{:LU('/presale/'.$item['id'])}">
				<div class="presale-cover">
					<div class="cover" style="background-image:url({$item.cover})"></div>
					<div class="inner">
                        <?php if($item['type']):?>
						<span class="presale-type">{$item.type}</span>
                        <?php endif;?>
					</div>
				</div>
				<div class="presale-info">
					<h3 class="presale-name">{$item.name}</h3>
					<p class="presale-price"><span>{$item.price}</span></p>
					<p class="presale-layout">{$item.layout} - {$item.area}</p>
					<p class="presale-location">{$item.country_name}·{$item.city_name}</p>
				</div>
			</a>
            <?php endforeach;?>
		</div>
	</div>
</div>
<?php endif;?>

<?php if($data['hot_buildings']):?>
<div class="section hot-buildings">
	<div class="container">
		<h2 class="section-title">{$data.lang.BEST_BUILDINGS}</h2>
		<div class="section-body">
            <?php foreach($data['hot_buildings'] as $k => $v):?>
			<a class="building-item" href="{:LU('/building/'.$v['id'])}" title="{$v.name}">
				<div class="building-cover">
					<div class="cover" style="background-image:url({$v.cover})"></div>
					<div class="inner">
                        <?php if($v['tag']):?>
						<span class="building-tag">{$v.tag}</span>
                        <?php endif;?>
					</div>
				</div>
				<div class="building-info">
					<h3 class="building-name">{$v.name}</h3>
					<p class="building-price"><span>{$v.price}</span><span class="sp">{$data.lang.SP}</span></p>
					<p class="building-location">{$v.location}</p>
				</div>
			</a>

            <?php endforeach;?>
		</div>
	</div>
</div>
<?php endif;?>

{include file='Common/footer' /}