{include file='Common/header_m' /}

<?php if($data['banner']):?>
<div class="swiper">
	<div class="swiper-container">
		<div class="swiper-wrapper">
            <?php foreach ($data['banner'] as $k => $v):?>
				<div class="swiper-slide">
                    <?php if($v['type'] == 1):?>
						<div class="image link-item" data-url="{:U($v['target'].'/'.$v['targetId'])}" style="background-image: url('{$v.file}')"></div>
                    <?php elseif ($v['type'] == 2):?>
						<div class="video" data-file="{$v.file}" style="background-image: url('{$v.file}?x-oss-process=video/snapshot,t_1000')">
							<img src="__PUBLIC__/img/icon_play.png" />
						</div>
                    <?php endif;?>
				</div>
            <?php endforeach;?>
		</div>
		<div class="swiper-pagination"></div>
	</div>
</div><!-- //轮播 -->
<?php endif;?>

<?php if($data['info']['feature']):?>
<div class="section building-intro">
	<div class="section-title">{$data.lang.CITY_IDENTITY}</div>
	<div class="section-body">
		<div>{$data.info.feature}</div>
	</div>
</div>
<?php endif;?>

<?php if($data['info']['building_intro']):?>
<div class="section building-intro">
	<div class="section-title">{$data.lang.BUILDING_INTRO}</div>
	<div class="section-body">
		<div>{$data.info.building_intro}</div>
	</div>
</div>
<?php endif;?>

<?php if($data['presales']):?>
<div class="section presales">
	<div class="section-title">{$data.lang.PRESALES_LIST}</div>
	<div class="section-body">
		<?php foreach ($data['presales'] as $k => $item):?>
		<div class="presale-item link-item" data-url="{:U('presale/'.$item['id'])}">
			<div class="presale-meta">
				<div class="presale-cover" style="background-image:url({$item.cover})"></div>
				<div class="presale-info">
					<?php if($item['name']):?>
					<span>{$item.name}</span>
					<?php endif;?>
					<?php if($item['type']):?>
					<span class="item-info">{$item.type} - {$item.area}</span>
					<?php endif;?>
                    <?php if($item['layout']):?>
					<span class="item-info">{$item.layout}</span>
                    <?php endif;?>
				</div>
			</div>
			<div class="presale-price">
				<span>{$item.price}</span>
			</div>
		</div>
        <?php endforeach;?>

		<button class="btn-more link-item" data-url="{:U('city/presales/id/'.$data['id'])}">{$data.lang.MORE_INFO}</button>
	</div>
</div><!-- //楼花转让 -->
<?php endif;?>

<?php if($data['buildings']):?>
<div class="section buildings">
    <div class="section-title">{$data.lang.RELATED_BUILDINGS}</div>
    <div class="section-body">
        <?php foreach ($data['buildings'] as $k => $item):?>
        <div class="building-item link-item" data-url="{:U('building/'.$item['id'])}">
            <div class="building-cover" style="background-image:url({$item.cover})">
                <?php if($item['tag']):?>
				<span class="building-tag">{$item.tag}</span>
				<?php endif;?>
            </div>
            <div class="building-info">
                <div class="building-name"><span>{$item.name}</span></div>
                <div class="building-location"><span>{$item.location}</span></div>
                <div class="building-price"><span>{$item.price}</span><text class="sp">{$data.lang.SP}</text></div>
                <button class="btn">{$data.lang.VIEW_MORE}</button>
            </div>
        </div>
        <?php endforeach;?>
	    <button class="btn-more link-item" data-url="{:U('city/buildings/id/'.$data['id'])}">{$data.lang.MORE_INFO}</button>
    </div>
</div><!-- //合作楼盘 -->

<?php endif;?>

{include file='Common/footer_m' /}