{include file='Common/header' /}
<div class="breadcrumb">
	<div class="container">
		<span><a rel="nofollow" href="{:LU('/')}">{$data.lang.HOMEPAGE}</a></span>
		<img src="__PUBLIC__/img/icon_arrow_right_s.png" alt="arrow right" />
		<span><a href="{:LU('/country/'.$data['info']['country_id'])}">{$data.info.country_name}</a></span>
		<img src="__PUBLIC__/img/icon_arrow_right_s.png" alt="arrow right" />
		<span>{$data.info.name}</span>
	</div>
</div>
<div class="city-banner">
    <?php if($data['banner_video']):?>

	<div class="city-video fl">
		<video poster="{$data.banner_video}?x-oss-process=video/snapshot,t_1000" controls>
			<source src="{$data.banner_video}" type="video/mp4">
		</video>
	</div>

    <?php else:?>

	<div class="city-image fl" style="background-image: url('<?=$data['banner_images'][1]['file']?>')"></div>

    <?php endif;?>

	<div class="city-image fl" style="background-image: url('<?=$data['banner_images'][0]['file']?>')">
		<div class="inner">
			<h2 class="city-name ">{$data.info.name}</h2>
			<div class="city-meta ">
				<p>{$data.lang.COUNTRY_OF_ORIGIN}：{$data.info.country_name}</p>
				<p>{$data.lang.AREA}：{$data.info.area}</p>
				<p>{$data.lang.CURRENCY}：{$data.info.currency}</p>
				<p>{$data.lang.EXCHANGE_RATE}：{$data.info.exchange_rate}</p>
			</div>
		</div>
	</div>
</div>
<div class="navbar" id="nav">
	<div class="container">
		<ul>
			<li data-target="city-feature">{$data.lang.CITY_IDENTITY}</li>
            <?php if($data['info']['building_intro']):?>
			<li data-target="building-intro">{$data.lang.REAL_ESTATE_MARKET}</li>
            <?php endif;?>
            <?php if($data['presales']):?>
			<li data-target="presales-list">{$data.lang.PRESALES_LIST}</li>
            <?php endif;?>
            <?php if($data['buildings']):?>
			<li data-target="hot-buildings">{$data.lang.RELATED_BUILDINGS}</li>
			<?php endif;?>
		</ul>
	</div>
</div>

<div class="section waypoint city-feature" id="city-feature">
	<div class="container">
		<h2 class="section-title ">{$data.lang.CITY_IDENTITY}</h2>
		<div class="section-body ">
			<dl class="hide">
				<dt>{$data.lang.LIVABLE_CITY_RANKING}</dt>
				<dd>{$data.info.livable_rank}</dd>
			</dl>
			<dl class="hide">
				<dt>{$data.lang.AREA}</dt>
				<dd>{$data.info.area}</dd>
			</dl>
			<dl class="hide">
				<dt>{$data.lang.CLIMATE}</dt>
				<dd>{$data.info.climate}</dd>
			</dl>
            <?php if($data['info']['school']):?>
			<dl>
				<dt>{$data.lang.SCHOOL}</dt>
				<dd>{$data.info.school}</dd>
			</dl>
            <?php endif;?>
			<?php if($data['info']['feature']):?>
			<dl>
				<dt>{$data.lang.FEATURE}</dt>
				<dd>{$data.info.feature}</dd>
			</dl>
			<?php endif;?>
		</div>
	</div>
</div>

<?php if($data['info']['building_intro']):?>
<div class="section waypoint building-intro" id="building-intro">
	<div class="container">
		<h2 class="section-title ">{$data.lang.REAL_ESTATE_MARKET}</h2>
		<div class="section-body ">
			{$data.info.building_intro}
		</div>
	</div>
</div>
<?php endif;?>

<?php if($data['presales']):?>
<div class="section waypoint presales-list" id="presales-list">
	<div class="container">
		<h2 class="section-title ">{$data.lang.PRESALES_LIST}</h2>
		<div class="section-body ">
            <?php foreach ($data['presales'] as $k => $item):?>
            <a class="presale-item" href="{:LU('/presale/'.$item['id'])}">
	            <div class="presale-cover">
		            <div class="cover" style="background-image:url({$item.cover}?x-oss-process=image/resize,w_400)"></div>
		            <div class="inner">
                        <?php if($item['type']):?>
				            <span class="presale-type">{$item.type}</span>
                        <?php endif;?>
		            </div>
	            </div>
	            <div class="presale-info">
		            <h3 class="presale-name">{$item.name}</h3>
		            <p class="presale-price"><span>{$item.price}</span></p>
		            <p class="presale-layout">{$item.layout} - {$item.area}</p>
		            <p class="presale-location">{$item.country_name}·{$item.city_name}</p>
	            </div>
            </a>
            <?php endforeach;?>

			<a class="btn-more" href="{:LU('/city/presales/id/'.$data['id'])}">{$data.lang.MORE_INFO}</a>
		</div>
	</div>
</div>
<?php endif;?>

<?php if($data['buildings']):?>
<div class="section waypoint hot-buildings" id="hot-buildings">
	<div class="container">
		<h2 class="section-title ">{$data.lang.RELATED_BUILDINGS}</h2>
		<div class="section-body ">
            <?php foreach($data['buildings'] as $k => $v):?>
			<a class="building-item" href="{:LU('/building/'.$v['id'])}">
				<div class="building-cover">
					<div class="cover" style="background-image:url({$v.cover})"></div>
					<div class="inner">
                        <?php if($v['tag']):?>
						<span class="building-tag">{$v.tag}</span>
                        <?php endif;?>
					</div>
				</div>
				<div class="building-info">
					<h3 class="building-name">{$v.name}</h3>
					<p class="building-price"><span>{$v.price}</span><span class="sp">{$data.lang.SP}</span></p>
					<p class="building-location">{$v.location}</p>
				</div>
			</a>
            <?php endforeach;?>

			<a class="btn-more" href="{:LU('/city/buildings/id/'.$data['id'])}">{$data.lang.MORE_INFO}</a>
		</div>
	</div>
</div>
<?php endif;?>

{include file='Common/footer' /}