<div class="footer">
	<div class="container">
		<p>
			<a href="{:LU('/page/about_'.$data['current_lang'])}">{$data.lang.ABOUT_US}</a>
			<!-- &nbsp;&nbsp;&nbsp;&nbsp;<em>|</em>&nbsp;&nbsp;&nbsp;&nbsp; -->
			<!-- <a href="{:LU('/page/agreement')}">{$data.lang.AGREEMENT}</a>&nbsp;&nbsp;&nbsp;&nbsp;<em>|</em>&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="{:LU('/page/privacy')}">{$data.lang.PRIVACY}</a> -->
		</p>
		<p>
			<img class="logo" src="__PUBLIC__/img/img_logo_gray.png" />
		</p>
		<p class="copyright">
			{$data.lang.COPYRIGHT}<img src="__PUBLIC__/img/icon_icp.png" /><a href="http://beian.miit.gov.cn/" target="_blank">{$data.lang.ICP_NUMBER}</a>
		</p>
	</div>
</div>
<div class="sidebar animated" data-animate="fadeInRight">
	<div class="btn btn-top" id="btn-go-top"><img src="__PUBLIC__/img/icon_top.png" /></div>
	<div class="btn btn-link" id="btn-share"><img src="__PUBLIC__/img/icon_link.png" /></div>
	<div class="btn btn-wechat hide"><img src="__PUBLIC__/img/icon_wechat_white.png" /></div>
</div>

<div id="layer-lang-switcher" class="layer">
	<div class="inner">
		<a href="javascript:" class="close"></a>
		<h2>{$data.lang.SELECT_LANGUAGE}</h2>
		<a class="lang-item<?php if($data['current_lang'] == 'cn'):?> active<?php endif;?>" href="{:LU('', array('lang' => 'cn'))}">
			<h3>简体中文</h3>
			<p>China</p>
		</a>
		<a class="lang-item<?php if($data['current_lang'] == 'en'):?> active<?php endif;?>" href="{:LU('', array('lang' => 'en'))}">
			<h3>ENGLISH</h3>
			<p>United States</p>
		</a>
	</div>
</div>

<div id="layer-login" class="layer">
	<div class="inner">
		<a href="javascript:" class="close"></a>
		<div class="login-title"><em></em><span>{$data.lang.WEB_LOGIN_TITLE}</span><em></em></div>
		<div class="qrcode" data-url="{:LU('/login/wechat')}">
			<img src="__PUBLIC__/img/icon_wechat.png" />
		</div>
		<p>{$data.lang.WEB_LOGIN_INTRO}</p>
	</div>
</div>

<div id="layer-share" class="layer">
	<div class="inner">
		<a href="javascript:" class="close"></a>
		<div class="share-title"><em></em><span>{$data.lang.WEB_SHARE_TITLE}</span><em></em></div>
		<div class="qrcode" id="qrcode-share">
			<img class="wechat-logo" src="__PUBLIC__/img/icon_wechat.png" />
		</div>
		<p>{$data.lang.WEB_SHARE_INTRO}</p>
	</div>
</div>

<div id="layer-message" class="layer">
	<div class="inner">
		<a href="javascript:" class="close"></a>
		<div class="message-title"><em></em><span>{$data.lang.WEB_MESSAGE_TITLE}</span><em></em></div>
		<div class="message-body">
			<form action="{:LU('/message')}" method="post" id="msg-form" onsubmit="return false" autocomplete="off">
				<input type="hidden" name="type" value="1" />
				<input type="hidden" name="id" value="" />
				<div class="form-item">
					<label>{$data.lang.WEB_MESSAGE_FIELD_TEL}</label>
					<div>
						<input class="input" type="tel" name="tel" placeholder="{$data.lang.WEB_MESSAGE_TIP_TEL}" maxlength="20" />
					</div>
				</div>
				<div class="form-item">
					<label>{$data.lang.WEB_MESSAGE_FIELD_MSG}</label>
					<div>
						<textarea class="input" rows="3" type="text" name="msg" placeholder="{$data.lang.WEB_MESSAGE_TIP_MSG}"></textarea>
					</div>
				</div>
				<div class="form-item">
					<label>&nbsp;</label>
					<div>
						<button type="submit" id="btn-send">{$data.lang.WEB_MESSAGE_SUBMIT}</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">var module = "{$data.js_module}",shareUrl = "https://www.squirreal.cn/share?{$data.shareUrl}";</script>
<?php build_js(isset($data['js']) ? $data['js'] : '')?>
</body>
</html>