<!DOCTYPE html>
<html>
<script>
	var _hmt = _hmt || [];
	(function() {
	var hm = document.createElement("script");
	hm.src = "https://hm.baidu.com/hm.js?c323d9980573072b781964ade613f536";
	var s = document.getElementsByTagName("script")[0]; 
	s.parentNode.insertBefore(hm, s);
	})();
</script>
<head>
<meta charset="utf-8" />
<title>{$data.title}</title>
<meta name="keywords" content="squirreal,海外房产,海外投资,海外买房,海外买房移民,买房移民" />
<meta name="description" content="松鼠国际房产(www.squirreal.cn)是一个精品国际房地产资产配置平台, 为您提供最专业, 最优质的服务。">
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="renderer" content="webkit" />
<link rel="shortcut icon" href="/public/assets/img/favicon.ico" />
<meta name="keywords" content="{$data.keywords}" />
<meta name="description" content="{$data.description}" />
<meta name="robots" content="index, follow" />
<?php build_css(isset($data['css']) ? $data['css'] : '')?>
</head>
<body<?=body_class(isset($data['body_class']) ? $data['body_class'] : '')?>>
<?php if($data['body_class'] != 'home'):?>
<div class="top-banner">
	<div class="container">
		<a rel="nofollow" href="{:LU('/')}" class="logo " data-animate="fadeInDown"><img src="__PUBLIC__/img/img_logo_black.png" /> </a>
		<div class="menu " data-animate="fadeInDown">
			<a rel="nofollow" href="javascript:" class="btn-lang-switcher">
				<svg viewBox="0 0 12 12" class="icon-lang"><path d="M3.48 3.5c.17-.85.43-1.6.75-2.18A5.02 5.02 0 001.67 3.5zm1.03 0h2.98C7.16 2 6.57 1 6 1S4.84 2 4.5 3.5zm4 0h1.82a5.02 5.02 0 00-2.56-2.18c.32.58.58 1.33.75 2.18zm.16 1a13.82 13.82 0 010 3h2.1a5 5 0 000-3zm-1.01 0H4.34a12.43 12.43 0 000 3h3.32a12.43 12.43 0 000-3zm-4.33 0h-2.1a5 5 0 000 3h2.1a13.82 13.82 0 010-3zm5.19 4a7.5 7.5 0 01-.75 2.18 5.02 5.02 0 002.56-2.18zm-1.03 0H4.51C4.84 10 5.43 11 6 11s1.16-1 1.5-2.5zm-4 0H1.66c.57 1 1.48 1.77 2.56 2.18a7.5 7.5 0 01-.75-2.18zM6 12A6 6 0 116 0a6 6 0 010 12z" fill="currentcolor"></path></svg>
				<span>{$data.current_lang_name}</span>
			</a>
			<?php if($data['userinfo']):?>
			<div class="userinfo">
				<span>{$data.userinfo.nickname}</span>
				<img src="{$data.userinfo.avatar}" />
			</div>
			<?php else:?>
			<a rel="nofollow" href="javascript:" class="btn-login">{$data.lang.SIGN_IN}</a>
			<a rel="nofollow" href="javascript:" class="btn-login">{$data.lang.SIGN_UP}</a>
			<?php endif;?>
		</div>
	</div>
</div>
<?php endif;?>
